create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,display_name text,plan text not null default 'free' check(plan in('free','plus','pro','education','business')),role text not null default 'user' check(role in('user','admin')),created_at timestamptz default now());
create table if not exists public.usage_events(id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,event_type text not null,units integer not null default 1,created_at timestamptz default now());
create table if not exists public.saved_searches(id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,query text not null,result_snapshot jsonb,created_at timestamptz default now());
create table if not exists public.subscriptions(id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,provider text default 'paystack',plan text not null,status text default 'inactive',customer_code text,subscription_code text unique,current_period_end timestamptz,updated_at timestamptz default now());
alter table public.profiles enable row level security; alter table public.usage_events enable row level security; alter table public.saved_searches enable row level security; alter table public.subscriptions enable row level security;
revoke all on table public.profiles,public.usage_events,public.saved_searches,public.subscriptions from anon;
grant select,insert,update on public.profiles to authenticated; grant select,insert on public.usage_events to authenticated; grant select,insert,delete on public.saved_searches to authenticated; grant select on public.subscriptions to authenticated;
create policy "profile_select_own" on public.profiles for select to authenticated using ((select auth.uid())=id);
create policy "profile_insert_own" on public.profiles for insert to authenticated with check ((select auth.uid())=id);
create policy "profile_update_own" on public.profiles for update to authenticated using ((select auth.uid())=id) with check ((select auth.uid())=id);
create policy "usage_select_own" on public.usage_events for select to authenticated using ((select auth.uid())=user_id);
create policy "usage_insert_own" on public.usage_events for insert to authenticated with check ((select auth.uid())=user_id);
create policy "saved_select_own" on public.saved_searches for select to authenticated using ((select auth.uid())=user_id);
create policy "saved_insert_own" on public.saved_searches for insert to authenticated with check ((select auth.uid())=user_id);
create policy "saved_delete_own" on public.saved_searches for delete to authenticated using ((select auth.uid())=user_id);
create policy "subscription_select_own" on public.subscriptions for select to authenticated using ((select auth.uid())=user_id);


-- Automatically create a profile when a new Auth user is created.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
